### PR TITLE
Implemented client-side rendering.

### PR DESCRIPTION
**Pull request by sebastianhoitz**
This is a basic first step, to get the functionality out the door.
Later we should implement more robust path-building of the views via a separate store
for the client-side views.

On the server side, this is currently handled by the filesystem store.

I could imagine a "arraycache" store for the client-side, that is able to build the
required view path from the options. That way, we don't have to separate the logic
in the view renderer between server and client.

### CODE REVIEW

**Comment by lancejpollard** [comment]
You're the man, thanks!  Will push a new version soon with these changes.

**Comment by avastou** [comment]
I do not see how to use it.
Is this correct:

``` coffee
    item = @render "shared/application/_tweet", locals: tweet
    $(item).hide().prependTo(".tweet-container").fadeIn(1500);
```

because it seems not to work

**Comment by avastou** [comment]
this does not work, I think I know why.
File vendor/tower.js is not updated, it does not contain the commits (tower is installed with npm install tower - version 0.4.0-13).
How to update this ?

One more, I think this  (tower.js - line 6819): 
̀

```
result = this.constructor.cache[cachePath] || require('fs').readFileSync(path, 'utf-8').toString();
```

require("fs"); not working on client side

**Comment by lancejpollard** [comment]
try building the tower client js from source:

```
git clone git@github.com:viatropos/tower.git
cd tower
npm install
design.io
cake build # dist/tower.js
```

**Pull request merged**
