### PR TITLE
Complete Danish localization ;)

### PR DESCRIPTION
**Pull request by kristianmandrup**
Would be nice with a little "internal" generator to create stubs for the translation files...

### CODE REVIEW

**Comment by lancejpollard** [comment]
Good idea, added generator idea to the [roadmap](https://github.com/viatropos/tower/wiki/roadmap).

**Comment by kristianmandrup** [comment]
I would really like to chat with you so I can better help contribute. Could you please log onto Skype or whichever channel you prefer, thanks :)

**Comment by lancejpollard** [comment]
I'll login to skype later today (4-5ish).  I've also started an IRC group at channel #towerjs.  We should start using that.

**Comment by kristianmandrup** [comment]
OK, I'm on the IRC channel... I'm reading through the wiki while trying to fix/improve it a little.

**Pull request merged**
