### PR TITLE
support stylus-lemonade plugin

### PR DESCRIPTION
**Pull request by mikesmullin**
[stylus-lemonade](https://github.com/mikesmullin/stylus-lemonade) is my plugin. i am using it with stylus to generate css sprite images automatically. it is inspired by and closely follows the standard set in the Rails community ala Spriting with Compass/SASS formerly "Lemonade". of course people can always include this package manually but if you feel like spriting should be an out-of-the-box feature as it is with RoR, then plz consider linking it as a dependency (see attached commit)

thanks and best wishes

### CODE REVIEW

**Comment by mikesmullin** [comment]
fyi: it breaks the travis build because ubuntu needs a lib installed for the node-gd bindings to work. something about that would also need to be added to Tower installation process.

``` bash
sudo apt-get install libgd2-xpm-dev # on ubuntu, for css image sprite processing
```

btw including the dependency is all we need for it to start working with Tower assuming this pull request (https://github.com/gruntjs/grunt-contrib-stylus/pull/6) for grunt-contrib-stylus is approved. i noticed [mint.js is also capable of compiling stylus](https://github.com/viatropos/mint.js/blob/master/src/mint.coffee#L86) but doesn't seem to actually handle any of it in the Tower project; let me know if i am wrong about that assumption.

**Comment by thehydroimpulse** [comment]
@mikesmullin They'll be a dependency problem `libgd2-xpm-dev` being only for linux. Tower would need to work for all platforms.

**Comment by mikesmullin** [comment]
ya true i may have to do some cross-platform testing to find the install instructions for OS/X and Windows. FWIW the [node-gd](https://github.com/andris9/node-gd) install instructions only list a dependency issue for Ubuntu, but it could be that that's all they've tested, as well. :/

**Comment by mikesmullin** [comment]
well people can add it easily enough with `npm install stylus-lemonade --save` if they want.

**Pull request closed without merging**
