### PR TITLE
0.5! BAM!

### PR DESCRIPTION
**Pull request by thehydroimpulse**

### CODE REVIEW

**Comment by pethin** [comment]
Nice! Can't wait! :smiley:

**Comment by octopusinc** [comment]
Let's get this party started!  I'm waiting on you guys to push this out so I don't have to downgrade Node.

**Comment by thehydroimpulse** [comment]
@octopusinc We're almost ready.

**Comment by octopusinc** [comment]
Nice work!  I'm excited…

**Comment by lancejpollard** [comment]
Done.

**Comment by edubkendo** [comment]
WOOT!!

**Pull request merged**
