### PR TITLE
Update grunt to >= 0.4.0

### PR DESCRIPTION
**Pull request by pethin**

### CODE REVIEW

**Comment by pocesar** [comment]
nice pull

**Comment by pethin** [comment]
Thanks! I'm going to try to fix the Travis CI build tonight. It might not be done until tomorrow though.

**Comment by pethin** [comment]
Fixing the builder had a ton of issues and since grunt is going to be (mostly?) removed in light of a bundler; the refactorization of the code is practically useless.

**Comment by thehydroimpulse** [comment]
@Cacteye Are you talking about 0.5.0?

**Comment by pethin** [comment]
Yes, I am

**Comment by thehydroimpulse** [comment]
@Cacteye Yes. Grunt is gone for 0.5.0. Tower will only use a single console tab to operate, instead of two. Were opting for an extremely light-weight bundler.

**Comment by pethin** [comment]
@TheHydroImpulse Will it be removed for the compilation too? I know that you stated that the source will be written in JavaScript instead of CoffeeScript.

**Comment by thehydroimpulse** [comment]
@Cacteye Yes. The bundler or bundle will perform everything regarding to assets. JavaScript is the primary language.

**Comment by lancejpollard** [comment]
I can merge this in the meantime, can anyone verify that this works?

**Comment by wamatt** [comment]
Is tower.js still being worked on?

**Comment by thehydroimpulse** [comment]
@wamatt http://github.com/tower #0.5

**Comment by pethin** [comment]
@wamatt Also a great link to @TheHydroImpulse 's blog post: http://hydrocodedesign.com/blog/2013/01/18/whats-up-with-tower-dot-js/

**Comment by thehydroimpulse** [comment]
@wamatt @Cacteye Although that's greatly outdated, it might be useful. Once we release 0.5.0, we'll be very public on what's going on.

**Comment by wamatt** [comment]
@Cacteye @TheHydroImpulse  thanks chaps. I see, yeah, maybe throw up a link on the readme of this repo?. Easy to assume it's been abandoned.

0.5 looks great. I'm assuming the new home will be https://github.com/tower and that's where the action is happening?

Also it looks like it will be more heavily componentized (is that a word hehe)? Kinda like what socketstream was trying to do?

**Comment by thehydroimpulse** [comment]
@wamatt We don't want to draw too much attention yet, at least not until it's ready. That's why there isn't anything on there. 

Yes, that's the new home and it's also composed of components.

**Comment by wamatt** [comment]
@TheHydroImpulse ok. Look forward to reading about the 0.5 when you launch. Good luck :+1:

**Pull request closed without merging**
