### PR TITLE
Adding rails like index html

### PR DESCRIPTION
**Pull request by krainboltgreene**
Created a helpful index.html file for newbies to see when they first launch the application, much like Rails.
It gives them details on how to setup Tower.js as well as how to get help.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
Haha, ok, so different icon. I couldn't find one, and I'm no artist!

What kind of "tower" would you want? Tower of Babel? Office Tower? etc?

Tower.js feels like, to me, it's the best framework for _getting things shipped_. Some imagery that fits that would be awesome.

**Comment by krainboltgreene** [comment]
Re: Static File

I definitely agree with you on the static bit. Having to remove it every time sucks, in Rails.

So we can do this two ways:
1. We can have a flag like --no-static, never creates it. This also leaves open to the idea of having a .towerrc file that populates the options field for pro-users.
2. A dynamic file.

Number 2 brings the problem of Foundation Vs. Bootstrap. I built the index page using Foundation because it was suuuuper simple and different.

**Comment by lancejpollard** [comment]
We shouldn't use a `--no-static` option b/c that makes it a little more difficult for the newcomer, and they're the one most likely to be confused by why their root route isn't working right.

I haven't thought that much about having a custom `.towerrc` file, will consider it more over the next few weeks. But I would like to try to avoid that b/c there's already too many vendor-specific dotfiles in the community, and to me it would make tower feel less flexible for some reason - like we have all these custom build scripts and configuration to get it working. What do you think? Maybe in the future with a larger/regular community, then adding that would feel like the next logical step.

I don't know what Foundation is, will check that out! If it's an alternative to Twitter Bootstrap we should reconsider including it. I'm over the default Twitter Bootstrap design. Soon we should create a simple/plain "tower generated app" twitter bootstrap theme, and use that for this index.coffee file, all put into `app/client/stylesheets/application.styl`. We should be able to use the same set of styles - minimal minimal styles, like [what express gives you](https://github.com/visionmedia/express/blob/master/bin/express#L145), maybe a little more :) - for the default error pages as well.

**Comment by krainboltgreene** [comment]
You could add copy to the index.html saying to delete it next.

Again, the only problem with the dynamic one is the Foundation Vs.
Bootstrap. I don't the page will look half as good using bootstrap,
but I'd be willing to look at it. I'm beginning to really like
Foundation over Bootstrap.

On Sun, Jul 29, 2012 at 6:39 AM, Lance Pollard
reply@reply.github.com
wrote:

> We shouldn't use a `--no-static` option b/c that makes it a little more difficult for the newcomer, and they're the one most likely to be confused by why their root route isn't working right.
> 
> I haven't thought that much about having a custom `.towerrc` file, will consider it more over the next few weeks. But I would like to try to avoid that b/c there's already too many vendor-specific dotfiles in the community, and to me it would make tower feel less flexible for some reason - like we have all these custom build scripts and configuration to get it working. Maybe in the future with a larger/regular community, then adding that would feel like the next logical step.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/viatropos/tower/pull/177#issuecomment-7352144

## 

Kurtis Rainbolt-Greene, Hacker
Difference Engineers, LLC
643 Magazine St. #102
New Orleans, LA 70130

**Comment by lancejpollard** [comment]
We should add a command-line option for saying either "no css framework" or which one you want (bootstrap, foundation, etc.). Something like [src/tower/server/command/new.coffee#L20](https://github.com/viatropos/tower/blob/3f5a787e4c1c06beb58210a5cab2041aebafbff3/src/tower/server/command/new.coffee#L20) (it's not implemented anywhere).

**Comment by krainboltgreene** [comment]
I'll see what I can do.

**Comment by lancejpollard** [comment]
Closing this since we should implement generator options rather than static html.

**Pull request closed without merging**
