### PR TITLE
Fixes problem with delete action so that it properly syncs between all c...

### PR DESCRIPTION
**Pull request by edubkendo**
...lients.

I figured I should go ahead and commit this and get the initial pull request in, since delete is working. I'll continue hacking on update and add that commit to this PR if I get it solved.

### CODE REVIEW

**Comment by edubkendo** [comment]
Got the updates. Wow, trickiest "bug" I've ever had the "pleasure" of tracking down and fixing. Thankfully, Chrome Dev. Tools made it a lot easier to do than would have been otherwise. Now maybe I can get some sleep. Was quite cool seeing all these actions finally working in sync in two browsers.

**Comment by lancejpollard** [comment]
WIll get to this in a bit, thanks a lot for tracking this down and fixing it. Awesome stuff.

**Comment by edubkendo** [comment]
Ah no, I think you are right about that isDirty, i was trying that at one point and just forgot to change it back.

**Comment by lancejpollard** [comment]
No worries, I'll change it back. Thanks though, merged and it's all working :)

**Comment by edubkendo** [comment]
word. found that reload method, btw, by setting debugger in the middle of that load method and then just typing "record." into chrome's console scrolling through the suggestions trying different ones and seeing if it caused the update to finish

**Pull request merged**
