### PR TITLE
Install help

### PR DESCRIPTION
**Pull request by lancejpollard**
What do you guys think of this? Basically this branch adds a post-install message like this:

```
/--------------------------------------------------------------------------\
|                                                                          |
|  Tower is installed!                                                     |
|                                                                          |
|  Create an app:                                                          |
|                                                                          |
|    $ tower new app                                                       |
|    $ cd app                                                              |
|    $ npm install                                                         |
|    $ tower generate scaffold post title:string body:text belongsTo:user  |
|    $ tower generate scaffold user email:string hasMany:posts             |
|    $ cake watch                                                          |
|    $ node server                                                         |
|                                                                          |
|  More info:                                                              |
|                                                                          |
|    IRC:      #towerjs                                                    |
|    Docs:     http://github.com/viatropos/tower/wiki                      |
|    Roadmap:  https://github.com/viatropos/tower/blob/master/ROADMAP.md   |
|                                                                          |
\--------------------------------------------------------------------------/
```

If you have heroku installed, it will also insert  this:

```
|  Deploy to Heroku:                                                       |
|                                                                          |
|    $ cake assets:bundle                                                  |
|    $ git init                                                            |
|    $ git add .                                                           |
|    $ git commit -a -m "first commit"                                     |
|    $ heroku create                                                       |
|    $ git push heroku master                                              |
```

If you don't have mongodb, coffee-script, or git installed it will say something like this at the top:

```
|  Please install git and mongodb before continuing:                       |
|                                                                          |
|    $ brew install git                                                    |
|    $ brew install mongodb                                                |
```

[todo] Add mappings for linux and windows on how to install these different things (it will just say install them w/o the instructions for now).

If you have node < 0.8, it will show a note in yellow saying you should update, if node < 0.6 then it will be in red saying it's unsupported:

```
|  Tower is installed!                                                     |
|                                                                          |
|  Note: You are using an unsupported version of node (v0.4.7).            |
|  Please upgrade to the latest version of node (>= v0.8.2).               |
|                                                                          |
|  Create an app:                                                          |
```

Any thoughts?

### CODE REVIEW

**Comment by thehydroimpulse** [comment]
I'm really digging that installation setup! Will definitely help people out when they adopt to Tower.

**Comment by edubkendo** [comment]
For linux, 

to install coffeescript:

```
npm install -g coffee-script
```

MongoDB:

```
http://www.mongodb.org/display/DOCS/Quickstart
```

I was going to list the specific instructions for installing mongodb on ubuntu, but it is actually several steps, so just linking to the install guide is probably best, at least to get the proper version of it. Also, that would be ubuntu specific, but this way its applicable for all linux users.

**Comment by lancejpollard** [comment]
Good point, I'll probably just have it say something like this:

```
Please install git and mongodb before continuing:

  http://github.com/viatropos/tower/wiki/Development Environment
```

Also, going to have this only run when installed globally, since it would probably be overkill printing this out when installing in every app (since the instructions are pretty much for creating an app anyway).

**Comment by edubkendo** [comment]
best directions for installing git: http://git-scm.com/book/ch1-4.html . Guess I could just go update the wiki with these since you're gonna point there.

**Comment by lancejpollard** [comment]
Perfect, that'll work, yeah that'd be good on the wiki.

**Comment by lancejpollard** [comment]
This is definitely going to need more robust testing to make the "dependency checks" better (such as checking for sudo, or if rvm is installed then their default gemset for heroku, etc.). Eventually this stuff could turn into a separate node module (independent from tower). It should eventually be able to check cross-platform for any installed script.

Going to merge it now, not pushing to npm yet though, few other things to do.

**Comment by edubkendo** [comment]
https://github.com/viatropos/tower/wiki/Development-environment is no longer a blank ;)

**Comment by lancejpollard** [comment]
Haha nice.

**Pull request merged**
