### PR TITLE
Coffeekup -> Coffeecup

### PR DESCRIPTION
**Pull request by vjsingh**
Converting Coffeekup -> Coffeecup, because coffeekup is now deprecated (I was trying to use yield and it broke, see https://github.com/mauricemach/coffeekup/issues/113).

Not sure whats going on with the empty lines. I believe I'm just removing spaces on empty lines, but wasn't sure so I put it in a separate commit.

I couldn't get design.io to work for some reason, so the js files aren't updated, so I can't test if this works.

Also, Mint might need to be updated also. But this is a start

### CODE REVIEW

**Comment by lancejpollard** [comment]
tests don't pass

**Comment by vjsingh** [comment]
design.io wasn't working (even after running design.io start and then watch, it didn't update my coffee files).

I'll try and get it to work, fix the patch and resubmit it.

**Comment by lancejpollard** [comment]
Thanks, yeah design.io has a ways to go.  What operating system are you on?  It only works on mac, but someone just added linux support.

**Comment by vjsingh** [comment]
Mac... design.io is working for my own Tower app, but not for the tower repo.

Specifically, in the top level tower folder:
design.io start&
design.io watch (says hooks are ready)
edit and save src/tower/view/rendering/coffee
lib/tower/view/rendering.js is not updated

**Pull request closed without merging**
