### PR TITLE
Issue #365 - Added destroy command

### PR DESCRIPTION
**Pull request by btbinhtran**
I added a destroy command, refactored generator code to work with Tower.root to make generate destroy commands testable within test/example app.

Color coded logger for create actions. Also bolded the logger actions.

Updated the ulimit in the Makefile to 1000, so it can work on OS X Lion.

Destroy command handles:
- Model
- View
- Controller
- Service
- Helper
- Mailer
- Template
- Library
- Scaffold

Need to look into handling namespaces like in Rails.
Example: 

**tower generate model Animal::Bird** would generate **app/models/animal/bird.rb**

and

**tower destroy model Animal::Bird** would delete **app/models/animal/bird.rb** and all the references.

### CODE REVIEW

**Comment by thehydroimpulse** [comment]
Could you concatenate all those commits into one?

**Comment by btbinhtran** [comment]
I concatenated all the commits into one which solves issue 365 and 371, but I'm not sure why the pull request closed on my end.

I had to revert my branch because I did some additional commits on top of master, then rebase.

When I pushed the rebased issue365destroycommand branch it closed the pull request.

Hope all is well.

**Comment by thehydroimpulse** [comment]
yeah that's weird. I heard Lance (viatropos) is fairly busy right now, so don't worry if your PR is sitting there for a little bit.

**Comment by edubkendo** [comment]
I sent him a message to take a look, so hopefully he'll get to this one soon.

**Pull request merged**
