### PR TITLE
Windows Support

### PR DESCRIPTION
**Pull request by thehydroimpulse**
Finally fixed Tower for windows. The steps are exactly the same as before. 

**Tip**
For me anyways, I cannot run make commands within the git terminal (windows). Make will crash. So make => cmd. Not sure if that's just me.

### CODE REVIEW

**Comment by thehydroimpulse** [comment]
There is currently a small error when generating a new app (within windows of course) and running 

``` bash
cake watch
```

after running:

``` bash
npm install
```

**Error**

```
C:\Users\Daniel\Documents\app_test>cake watch
CreateProcessW: The system cannot find the file specified.
```

If you search it up you find that it's apart of grunt: https://github.com/cowboy/grunt/issues/155

Just thought people should know that there is still a wall before working on windows but this might not be tower's fault.

**Comment by lancejpollard** [comment]
Can the `which` command in [node-which](https://github.com/isaacs/node-which/) be abstracted/included in the Makefile?

**Comment by lancejpollard** [comment]
For the `cake watch` error, if you do:

```
npm install which
```

then in the interactive `node`, I'm getting:

```
> require('which').sync('cake')
'/usr/local/bin/cake'
```

Does this mean windows users should be doing:

```
/usr/local/bin/cake watch
```

(or whatever the full path to the `cake` command is)?

If so, is there a way to transparently create an alias to it on windows? Maybe so that when you first `npm install tower -g`, it checks if `cake` exists, and if not, adds an alias. That would be nice.

**Comment by thehydroimpulse** [comment]
What doesn't work on mac? I'm trying it on mountain lion and so far everything seems fine.

**Comment by lancejpollard** [comment]
I'm on 10.6.7 (Snow Leopard) and `node bin/dependencies` just returns the string:

```
npm install stylus uglify-js mocha chai sinon eco mustache jade kue mongodb coffee-script coffeecup gzip chokidar knox socket.io socket.io-client fibers cli-table ttys cheerio colors
```

But if it's wrapped in the Makefile command you made:

```
install-dependencies:
    $(shell $(DEPENDENCIES))
```

it works fine. It works with package.json `postinstall: "make install-dependencies"`. Does that work for you?

**Comment by lancejpollard** [comment]
Thank you by the way, this is very cool having the dev environment work on windows.

**Comment by thehydroimpulse** [comment]
Yeah that works but just running `node bin/dependencies` does print out text and it's because of the missing `$()`. Writting `$(bin/dependencies)` or `$(./bin/dependencies)` works fine.

**Comment by thehydroimpulse** [comment]
@viatropos No worries. Helps expand things a little.

**Comment by thehydroimpulse** [comment]
But I guess that brings us back to the original problem.

**Comment by lancejpollard** [comment]
Hmm...what is that? The `make install-dependencies` works for me, does it not you?

Lol, but now that fix to [tower/server.coffee](https://github.com/TheHydroImpulse/tower/commit/aa7439c4ddfe27e1b92fe7cf31c90177846626a4) with the `path.sep.length > 1` doesn't work on travisci, since everything is in a top-level directory:

```
/home/app/config/shared/application
```

Is there an alternative solution that works on windows?

**Comment by thehydroimpulse** [comment]
Ok. Yes the `make install-dependencies` does work and I changed that in the new pull request.

**Comment by thehydroimpulse** [comment]
So `path != _path.sep` instead of `path.sep.length > 1`?

**Comment by lancejpollard** [comment]
Cool. I tried this and it's working for me and travisci, how about you?

https://github.com/viatropos/tower/commit/372a9cba0883f4956d48e4bfca66d3524e89ac1d#L92

**Comment by thehydroimpulse** [comment]
@viatropos Ok I think it may work now. Try this: 

``` coffee
while !Tower.testIfRoot(path) && path != _path.sep && !path.match /^([A-Za-z:]*){2}/`
```

**Comment by thehydroimpulse** [comment]
Because windows uses drives the root path is never `/` or `\`. When I printed every loop and it's value it ended up printing: `C:\`. But not everyone's master drive is `C:\`. Try to see if that works.

**Comment by thehydroimpulse** [comment]
It works on mountain lion so far.

**Comment by lancejpollard** [comment]
What if it was `while ... && !path.match(/(?:\\|\/)$/)` or something like that?

**Comment by thehydroimpulse** [comment]
Yup that works too.

**Pull request merged**
